import {
  Projector,
  MonitorSmartphone,
  Wifi,
  Music2,
  Coffee,
  Airplay,
  PanelTop,
  Thermometer,
  Sun,
  Currency,
  Volume2,
  Armchair,
  Table2Icon,
  Lightbulb,
  PanelLeftClose,
  Lightbulb as LightbulbIcon,
  FileText,
} from "lucide-react";

export const facilityOptions = [
  { value: "Projector", label: "Proyektor", icon: Projector },
  { value: "Whiteboard", label: "Papan Tulis", icon: PanelTop },
  {
    value: "Video Conferencing",
    label: "Video Konferensi",
    icon: MonitorSmartphone,
  },
  { value: "Wi-Fi", label: "Wi-Fi", icon: Wifi },
  { value: "Sound System", label: "Sistem Audio", icon: Music2 },
  { value: "Refreshments", label: "Konsumsi", icon: Coffee },
  { value: "Screen Sharing", label: "Berbagi Layar", icon: Airplay },
  {
    value: "Teleconferencing",
    label: "Telekonferensi",
    icon: MonitorSmartphone,
  },
  { value: "Flipchart", label: "Kertas Flipchart", icon: FileText },
  { value: "Air Conditioning", label: "AC", icon: Thermometer },
  { value: "Heating", label: "Pemanas", icon: Thermometer },
  { value: "Natural Light", label: "Cahaya Alami", icon: Sun },
  { value: "Blackout Curtains", label: "Tirai Penghalang", icon: Currency },
  { value: "Soundproofing", label: "Kedap Suara", icon: Volume2 },
  { value: "Ergonomic Chairs", label: "Kursi Ergonomis", icon: Armchair },
  { value: "Standing Desks", label: "Meja Berdiri", icon: Table2Icon },
  {
    value: "Adjustable Lighting",
    label: "Pencahayaan Dapat Diatur",
    icon: Lightbulb,
  },
  { value: "Acoustic Panels", label: "Panel Akustik", icon: PanelLeftClose },
  { value: "Smart Lighting", label: "Pencahayaan Pintar", icon: LightbulbIcon },
];
