import {
  Projector,
  MonitorSmartphone,
  Wifi,
  Music2,
  Coffee,
  Airplay,
  PanelTop,
  Thermometer,
  Sun,
  Currency,
  Volume2,
  Armchair,
  Table2Icon,
  Lightbulb,
  PanelLeftClose,
  Lightbulb as LightbulbIcon,
  FileText,
} from "lucide-react";

export const facilityOptions = [
  { value: "Projector", label: "Projector", icon: Projector },
  { value: "Whiteboard", label: "Whiteboard", icon: PanelTop },
  {
    value: "Video Conferencing",
    label: "Video Conferencing",
    icon: MonitorSmartphone,
  },
  { value: "Wi-Fi", label: "Wi-Fi", icon: Wifi },
  { value: "Sound System", label: "Sound System", icon: Music2 },
  { value: "Refreshments", label: "Refreshments", icon: Coffee },
  { value: "Screen Sharing", label: "Screen Sharing", icon: Airplay },
  {
    value: "Teleconferencing",
    label: "Teleconferencing",
    icon: MonitorSmartphone,
  },
  { value: "Flipchart", label: "Flipchart", icon: FileText },
  { value: "Air Conditioning", label: "Air Conditioning", icon: Thermometer },
  { value: "Heating", label: "Heating", icon: Thermometer },
  { value: "Natural Light", label: "Natural Light", icon: Sun },
  { value: "Blackout Curtains", label: "Blackout Curtains", icon: Currency },
  { value: "Soundproofing", label: "Soundproofing", icon: Volume2 },
  { value: "Ergonomic Chairs", label: "Ergonomic Chairs", icon: Armchair },
  { value: "Standing Desks", label: "Standing Desks", icon: Table2Icon },
  {
    value: "Adjustable Lighting",
    label: "Adjustable Lighting",
    icon: Lightbulb,
  },
  { value: "Acoustic Panels", label: "Acoustic Panels", icon: PanelLeftClose },
  { value: "Smart Lighting", label: "Smart Lighting", icon: LightbulbIcon },
];
